/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatifRouteImport } from './routes/whatif'
import { Route as TurdRouteImport } from './routes/turd'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as DepsRouteImport } from './routes/deps'
import { Route as CoherenceRouteImport } from './routes/coherence'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BlockRouteImport } from './routes/block'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlockIndexRouteImport } from './routes/block.index'
import { Route as IconsSplatRouteImport } from './routes/icons.$'
import { Route as BlockIdRouteImport } from './routes/block.$id'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiBackupRouteImport } from './routes/api.backup'

const WhatifRoute = WhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => rootRouteImport,
} as any)
const TurdRoute = TurdRouteImport.update({
  id: '/turd',
  path: '/turd',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const DepsRoute = DepsRouteImport.update({
  id: '/deps',
  path: '/deps',
  getParentRoute: () => rootRouteImport,
} as any)
const CoherenceRoute = CoherenceRouteImport.update({
  id: '/coherence',
  path: '/coherence',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockRoute = BlockRouteImport.update({
  id: '/block',
  path: '/block',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockIndexRoute = BlockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlockRoute,
} as any)
const IconsSplatRoute = IconsSplatRouteImport.update({
  id: '/icons/$',
  path: '/icons/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockIdRoute = BlockIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlockRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupRoute = ApiBackupRouteImport.update({
  id: '/api/backup',
  path: '/api/backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/block': typeof BlockRouteWithChildren
  '/browse': typeof BrowseRoute
  '/coherence': typeof CoherenceRoute
  '/deps': typeof DepsRoute
  '/factory': typeof FactoryRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/turd': typeof TurdRoute
  '/whatif': typeof WhatifRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/chat': typeof ApiChatRoute
  '/block/$id': typeof BlockIdRoute
  '/icons/$': typeof IconsSplatRoute
  '/block/': typeof BlockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/browse': typeof BrowseRoute
  '/coherence': typeof CoherenceRoute
  '/deps': typeof DepsRoute
  '/factory': typeof FactoryRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/turd': typeof TurdRoute
  '/whatif': typeof WhatifRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/chat': typeof ApiChatRoute
  '/block/$id': typeof BlockIdRoute
  '/icons/$': typeof IconsSplatRoute
  '/block': typeof BlockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/block': typeof BlockRouteWithChildren
  '/browse': typeof BrowseRoute
  '/coherence': typeof CoherenceRoute
  '/deps': typeof DepsRoute
  '/factory': typeof FactoryRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/turd': typeof TurdRoute
  '/whatif': typeof WhatifRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/chat': typeof ApiChatRoute
  '/block/$id': typeof BlockIdRoute
  '/icons/$': typeof IconsSplatRoute
  '/block/': typeof BlockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/block'
    | '/browse'
    | '/coherence'
    | '/deps'
    | '/factory'
    | '/mcp'
    | '/settings'
    | '/tasks'
    | '/turd'
    | '/whatif'
    | '/api/backup'
    | '/api/chat'
    | '/block/$id'
    | '/icons/$'
    | '/block/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/browse'
    | '/coherence'
    | '/deps'
    | '/factory'
    | '/mcp'
    | '/settings'
    | '/tasks'
    | '/turd'
    | '/whatif'
    | '/api/backup'
    | '/api/chat'
    | '/block/$id'
    | '/icons/$'
    | '/block'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/block'
    | '/browse'
    | '/coherence'
    | '/deps'
    | '/factory'
    | '/mcp'
    | '/settings'
    | '/tasks'
    | '/turd'
    | '/whatif'
    | '/api/backup'
    | '/api/chat'
    | '/block/$id'
    | '/icons/$'
    | '/block/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  BlockRoute: typeof BlockRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  CoherenceRoute: typeof CoherenceRoute
  DepsRoute: typeof DepsRoute
  FactoryRoute: typeof FactoryRoute
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TurdRoute: typeof TurdRoute
  WhatifRoute: typeof WhatifRoute
  ApiBackupRoute: typeof ApiBackupRoute
  ApiChatRoute: typeof ApiChatRoute
  IconsSplatRoute: typeof IconsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatif': {
      id: '/whatif'
      path: '/whatif'
      fullPath: '/whatif'
      preLoaderRoute: typeof WhatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turd': {
      id: '/turd'
      path: '/turd'
      fullPath: '/turd'
      preLoaderRoute: typeof TurdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deps': {
      id: '/deps'
      path: '/deps'
      fullPath: '/deps'
      preLoaderRoute: typeof DepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coherence': {
      id: '/coherence'
      path: '/coherence'
      fullPath: '/coherence'
      preLoaderRoute: typeof CoherenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block': {
      id: '/block'
      path: '/block'
      fullPath: '/block'
      preLoaderRoute: typeof BlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block/': {
      id: '/block/'
      path: '/'
      fullPath: '/block/'
      preLoaderRoute: typeof BlockIndexRouteImport
      parentRoute: typeof BlockRoute
    }
    '/icons/$': {
      id: '/icons/$'
      path: '/icons/$'
      fullPath: '/icons/$'
      preLoaderRoute: typeof IconsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block/$id': {
      id: '/block/$id'
      path: '/$id'
      fullPath: '/block/$id'
      preLoaderRoute: typeof BlockIdRouteImport
      parentRoute: typeof BlockRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup': {
      id: '/api/backup'
      path: '/api/backup'
      fullPath: '/api/backup'
      preLoaderRoute: typeof ApiBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlockRouteChildren {
  BlockIdRoute: typeof BlockIdRoute
  BlockIndexRoute: typeof BlockIndexRoute
}

const BlockRouteChildren: BlockRouteChildren = {
  BlockIdRoute: BlockIdRoute,
  BlockIndexRoute: BlockIndexRoute,
}

const BlockRouteWithChildren = BlockRoute._addFileChildren(BlockRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  BlockRoute: BlockRouteWithChildren,
  BrowseRoute: BrowseRoute,
  CoherenceRoute: CoherenceRoute,
  DepsRoute: DepsRoute,
  FactoryRoute: FactoryRoute,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TurdRoute: TurdRoute,
  WhatifRoute: WhatifRoute,
  ApiBackupRoute: ApiBackupRoute,
  ApiChatRoute: ApiChatRoute,
  IconsSplatRoute: IconsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
